Wait for Appium startup

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,7 @@ jobs:
       CI: true
       APPIUM_TEST_SERVER_PORT: 4567
       APPIUM_TEST_SERVER_HOST: 127.0.0.1
+      APPIUM_STARTUP_TIMEOUT_SEC: 30
       DISPLAY: :10
       _FORCE_LOGS: 1
     runs-on: ubuntu-latest
@@ -68,6 +69,17 @@ jobs:
           2>&1 > "$cwd/appium.log" &
         popd
       name: Start Appium server
+    - run: |
+        seconds_started=$(date +%s)
+        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+          sleep 0.1
+          seconds_elapsed=$(( $(date +%s) - seconds_started ))
+          if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
+            echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
+            exit 1
+          fi
+        done
+      name: Wait for Appium server startup
     - run: npm run e2e-test
       name: Run functional tests
     - name: Save server output
